# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 박영재
title: Java & Spring 백엔드 엔지니어
email: pjok1122@gmail.com
website: https://blog.naver.com/pjok1122

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  pjok1122

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring 백엔드 개발자로 라인 페이에서 3개의 컴포넌트에 대해 `Ownership`을 가지고 있으며 설계와 개발을 주요 업무로 하고 있습니다. 컴포넌트에 대한 오너십을 가지고 있기 때문에 신규 피쳐나 프로젝트 개발 외에도 `주도적으로` 기술 부채를 제거하거나 운영 리소스를 줄이기 위해 Admin/Batch 등을 개발하는 등의 업무도 진행해왔습니다. 
  
  `코드리뷰` 에 대해 거부감이 없으며, 더 좋은 코드와 아키텍쳐를 설계하기 위해 팀과 논의하는 것을 좋아합니다.

  `가독성`과 `퍼포먼스` 모두 중요하게 생각하며, 기획과 요건에 따라 이 둘 사이의 trade off를 고려하여 설계하는 것을 즐깁니다.

  `테스트코드`와 Sanity test를 매우 중요하게 여기며, 사내 코드에 대해서는 Conditional coverage `80%` 이상을 유지해왔고, sonarqube 정적분석을 통해 code smell을 제거해왔습니다.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: ad-delivery
        caption: 2022.04 ~ 
        link: github.com/pjok1122/resume/tree/master/project/2022/04.마케팅플랫폼_AD-delivery.md
        link_text: 상세 보기
        quote: >
          ad-delivery 서비스 설계 및 개발
        description: | 
          - 컴포넌트 아키텍쳐 `설계`
          - `batch`를 이용한 마케팅 상품 동기화 설계 및 개발
          - `kafka`를 이용한 점포 정보 동기화 설계 및 개발
          - `webflux`를 이용한 마케팅 상품 조회 API 개발
          - 성능 테스트 진행 중..

      - layout: left
        border: weak
        title: mkt platform(LPGP)
        caption: 2022.04 ~ 
        link: github.com/pjok1122/resume/tree/master/project/2022/03.마케팅플랫폼_LPGP.md
        link_text: 상세 보기
        quote: >
          Line Pay Good Partner 앱에 마케팅 상품 판매 기능 추가
        description: |
          - LinePay Good Partner 앱을 통해 마케팅 상품을 구매할 수 있도록 Proxy 기능 개발 

      - layout: left
        border: weak
        title: merchant-map
        caption: 2020.12 ~ 2022.08
        quote: >
          Merchant map 컴포넌트 개발 & 운영
        description: |
          - [머천트맵 서비스 대만으로 이관](https://github.com/pjok1122/resume/tree/master/project/2022/05.머천트맵_대만이관.md)
          - [핫플레이스 및 담당자 추천 배지 기능 설계 및 개발](https://github.com/pjok1122/resume/tree/master/project/2022/01.머천트맵_목록개편.md)
          - [점포 이벤트 기능 설계 및 개발](https://github.com/pjok1122/resume/tree/master/project/머천트맵_상세페이지개편.md)
          - [키워드 필터링 프로젝트 매니징](https://github.com/pjok1122/resume/tree/master/project/2021/11.머천트맵_키워드필터링.md)
          - [카테고리 확장 기능 개발](https://github.com/pjok1122/resume/tree/master/project/2021/03.머천트맵_카테고리_확장.md)
          - 기타 SUS 기능 개발 및 운영.

      - layout: left
        border: weak
        title: IDC migration
        caption: 2021.07 ~ 2021.09
        link: github.com/pjok1122/resume/tree/master/project/2021/07.IDC_마이그레이션.md
        link_text: 상세 보기
        quote: >
          KR IDC를 JP IDC로 이관.
        description: |
          - `Rollback`을 염두한 IDC 이관 절차 수립 및 진행.

      - layout: left
        border: weak
        title: LinePay Good Parnter
        caption: 2021.03 ~ 2021.06
        link: github.com/pjok1122/resume/tree/master/project/2021/04.대만_앱포스_출시.md
        link_text: 상세 보기
        quote: >
          일 거래 80만. LinePay Good Partner 앱. 거래/정산 내역 관리 기능 개발
        description: |
          - `멱등성`을 보장하는 일간/월간 거래내역 집계 기능 개발
          - 거래/정산내역 관리 기능 개발
          - 일 거래 `80만` 데이터, 집계 테이블을 이용해 조회 성능 `10ms`로 최적화
          - `batch timing issue`를 고려한 조회 API 설계
          - `6억개` 거래내역 마이그레이션

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Line Biz+
        sub_title: 서버 개발자
        caption: 2020.07.01 ~
        link: https://pay.line.me/
        quote: >
          가맹점, 혜택 시스템 개발 및 운영
        description: |
          - `merchant-map` 컴포넌트 개발 및 운영
          - `ad-delivery` 컴포넌트 설계 및 개발
          - `LinePay Good Partner` 앱 거래/정산 내역 관리 기능 개발
          - `Kuji(Hongbao)` 서비스 유지보수 및 운영
          - `benefit` 서비스 유지보수 및 운영
          - [인턴/신입 멘토](https://github.com/pjok1122/resume/tree/master/project/매니징.md)
  - title: Education
    layout: list
    content:
      - layout: left
        title: 서울시립대학교
        sub_title: 수학과
        caption: 2012 ~ 2019
        description: | 
          - `수석` 졸업
          - 컴퓨터 사이언스 전공 과목 `A+` 이수
  - title: 기타 활동
    layout: list
    content:
      - layout: left
        title: 암호분석경진대회
        caption: 2018.06 ~ 2018.09
        link: https://github.com/pjok1122/cryptanalysis-contest-2018
        link_text: 상세 보기
        description: | 
          - 모든 분야에서 최고점으로 `1등`하여 국방부장관상 수상
          - 3명으로 구성된 팀의 `팀장`으로 활동.
      - layout: left
        title: 암호 공모전
        sub_title: 문제풀이 분야
        link: https://github.com/pjok1122/cryptanalysis-contest-2018
        link_text: 상세 보기
        caption: 2018.06 ~ 2018.09
        description: | 
          - 문제풀이 분야 `3등`으로 장려상 수상
          - 3명으로 구성된 팀의 `팀장`으로 활동.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
